
url = 'https://demo.nopcommerce.com/'
click_regist ='class=ico-register'
firstname ='id=FirstName'
lasname ='id=LastName'
radio_button = 'Gender'
date = 'name=DateOfBirthDay'
month ='name=DateOfBirthMonth'
year ='name=DateOfBirthYear'
email = 'id=Email'
company ='id=Company'
regist_pass ='id=Password'
confirm_pass='id=ConfirmPassword'
button_regist ='name=register-button'
result ='class=result'
click_login='class=ico-login'
button_login='class=login-button'
result2='class=ico-logout'
search_box ='id=small-searchterms'
button_search='class=search-box-button'
search_laptop ='xpath=/html/body/div[6]/div[2]/ul[1]/li[1]/a'
click_laptop = 'xpath=/html/body/div[6]/div[3]/div/div[3]/div/div[2]/div[1]/div/div[1]/div/div/a'
build_pc ='xpath=/html/body/div[6]/div[3]/div/div[3]/div/div[2]/div[2]/div[2]/div/div/div[1]/div/div[2]/h2/a'
list_1 = 'name=product_attribute_1'
list_2 = 'name=product_attribute_2'
list_3 = 'xpath=//*[@id="product_attribute_input_3"]/ul/li[2]/label'
list_4 = 'xpath=//*[@id="product_attribute_input_4"]/ul/li[2]/label'
list_5_1= 'product_attribute_5_10'
list_5_2 ='product_attribute_5_11'
list_5_3= 'product_attribute_5_12'
add_to_cart = 'id=add-to-cart-button-1'
notif_add_to_card='class=bar-notification'
notif_close='class=close'

#check cart
click_cart='xpath=//*[@id="topcartlink"]/a/span[1]'
checkbox_tnc='name=termsofservice'
button_checkout='id=checkout'

#billing address
bill_firstname='id=BillingNewAddress_FirstName'
bill_country ='id=BillingNewAddress_CountryId'
bill_state='id=BillingNewAddress_StateProvinceId'
bill_city='id=BillingNewAddress_City'
bill_address1='id=BillingNewAddress_Address1'
bill_zip='id=BillingNewAddress_ZipPostalCode'
bill_phone='id=BillingNewAddress_PhoneNumber'
button_acc='class=button-1 new-address-next-step-button'
button_next1='class=new-address-next-step-button'
#shiping
shiping_method1='id=shippingoption_1'
button_next2='xpath=//*[@id="shipping-method-buttons-container"]/button'
button_next3='xpath=//*[@id="payment-method-buttons-container"]/button'
button_next4='xpath=//*[@id="payment-info-buttons-container"]/button'
button_confirm='class=confirm-order-next-step-button'
button_same_add='class=new-address-next-step-button'

#login klick flow